# Generated by Django 5.2.6 on 2025-09-15 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "cycle_type",
                    models.CharField(
                        choices=[("70/8", "70/8"), ("60/7", "60/7")],
                        default="70/8",
                        max_length=10,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("start_location", models.CharField(max_length=250)),
                ("pickup_location", models.CharField(max_length=250)),
                ("dropoff_location", models.CharField(max_length=250)),
                ("distance_miles", models.FloatField(blank=True, null=True)),
                ("route_geojson", models.JSONField(blank=True, null=True)),
                ("estimated_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.driver"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DutyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OFF", "Off Duty"),
                            ("SLEEPER", "Sleeper"),
                            ("DRIVE", "Driving"),
                            ("ON", "On Duty Not Driving"),
                        ],
                        max_length=10,
                    ),
                ),
                ("duration_minutes", models.IntegerField()),
                ("location", models.CharField(blank=True, max_length=250)),
                ("miles_at_event", models.FloatField(blank=True, null=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="api.trip",
                    ),
                ),
            ],
        ),
    ]
