# Generated by Django 5.2.6 on 2026-02-20 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.truck'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='vin',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='RegionalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., North America', max_length=100)),
                ('cycle_type', models.CharField(choices=[('70/8', '70/8'), ('60/7', '60/7')], max_length=10)),
            ],
            options={
                'unique_together': {('name', 'cycle_type')},
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='regional_rule_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.regionalrule'),
        ),
    ]
