# Generated by Django 5.0.7 on 2024-07-26 12:55

from django.db import migrations

# Define the data to be seeded
CONTINENTS = [
    "Africa",
    "Antarctica",
    "Asia",
    "Europe",
    "North America",
    "Oceania",
    "South America",
]
CYCLE_TYPES = ["70/8", "60/7"]

def create_regional_rules(apps, schema_editor):
    """
    This function is executed when the migration is applied.
    It loops through the continents and cycle types and creates a RegionalRule for each combination.
    """
    # We get the model from the versioned app registry;
    # this ensures we're using the version of the model that this migration expects.
    RegionalRule = apps.get_model('api', 'RegionalRule')
    
    for continent in CONTINENTS:
        for cycle in CYCLE_TYPES:
            # Using get_or_create to avoid creating duplicates if the data already exists
            RegionalRule.objects.get_or_create(name=continent, cycle_type=cycle)

def delete_regional_rules(apps, schema_editor):
    """
    This function is executed when the migration is un-applied (rolled back).
    It deletes the rules that were created.
    """
    RegionalRule = apps.get_model('api', 'RegionalRule')
    RegionalRule.objects.filter(name__in=CONTINENTS, cycle_type__in=CYCLE_TYPES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_trip_truck_alter_truck_vin_regionalrule_and_more'),
    ]

    operations = [
        # This operation runs our custom Python functions
        migrations.RunPython(create_regional_rules, delete_regional_rules),
    ]
